In [ ]:
# Duplicates 
# Identify 

# Step 1 : Identify Duplicates

# 1. Exact Duplicate

# ID   Name     Age
# 101  Aman     25
# 101  Aman     25  <-- Duplicate row 

# 2. Partial Duplicate

# ID    Name     Age
# 101  Aman     25
# 101  Aman     26  <-- Age differs

# 3. Near Duplicates

# ID   Name          	Age
# 101  Aman Krishna    	25
# 101  Aman K.        	25  <-- Minor name difference

# Step 2 : Analyze duplicates

In [2]:
import pandas as pd

In [3]:
data = {
    'Ticket_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
    'Customer_Name': ['Aman', 'Rohit', 'Sneha', 'Rohan', 'Aman', 'Priya', 'Priya', 'Priya', 'Aditya', 'Aditya', 'Aditya',
                      'Neha', 'Neha', 'Neha', 'Ravi', 'Ravi', 'Ravi', 'Sonali', 'Sonali', 'Sonali'],
    'Email': ['aman@email.com', 'rohit@email.com', 'sneha@email.com', 'rohan@email.com', 'aman@email.com',
              'priya@email.com', 'priya@email.com', 'priya@email.com', 'aditya@email.com', 'aditya@email.com', 'aditya@email.com',
              'neha@email.com', 'neha@email.com', 'neha@email.com', 'ravi@email.com', 'ravi@email.com', 'ravi@email.com',
              'sonali@email.com', 'sonali@email.com', 'sonali@email.com'],
    'Order_ID': ['ORD001', 'ORD002', 'ORD003', 'ORD004', 'ORD001', 'ORD005', 'ORD005', 'ORD005', 'ORD006', 'ORD006', 'ORD006',
                 'ORD007', 'ORD007', 'ORD007', 'ORD008', 'ORD008', 'ORD008', 'ORD009', 'ORD009', 'ORD009'],
    'Issue_Description': [ "I can't log in to my account", "Login is not working for me", "Unable to log in to my account", "How to reset my password?",
        "I am unable to login to my account", "My order is delayed", "My order is late", "Order not received yet",
        "I got the wrong item", "Received incorrect product", "Product delivered is different",
        "Refund not processed yet", "Still waiting for my refund", "My refund is not credited yet",
        "Received a damaged product", "The product I received is broken", "Item arrived with scratches",
        "How long does delivery take?", "When will my package arrive?", "Estimated delivery time?" ],
    'Date': ['2024-02-01', '2024-02-02', '2024-02-02', '2024-02-03', '2024-02-03', '2024-02-03', '2024-02-03', '2024-02-04',
             '2024-02-04', '2024-02-05', '2024-02-05', '2024-02-05', '2024-02-06', '2024-02-06', '2024-02-06', '2024-02-07',
             '2024-02-07', '2024-02-07', '2024-02-08', '2024-02-08']
}

df = pd.DataFrame(data)

In [4]:
df

,Ticket_ID,Customer_Name,Email,Order_ID,Issue_Description,Date
0,101,Aman,aman@email.com,ORD001,I can't log in to my account,2024-02-01
1,102,Rohit,rohit@email.com,ORD002,Login is not working for me,2024-02-02
2,103,Sneha,sneha@email.com,ORD003,Unable to log in to my account,2024-02-02
3,104,Rohan,rohan@email.com,ORD004,How to reset my password?,2024-02-03
4,105,Aman,aman@email.com,ORD001,I am unable to login to my account,2024-02-03
5,106,Priya,priya@email.com,ORD005,My order is delayed,2024-02-03
6,107,Priya,priya@email.com,ORD005,My order is late,2024-02-03
7,108,Priya,priya@email.com,ORD005,Order not received yet,2024-02-04
8,109,Aditya,aditya@email.com,ORD006,I got the wrong item,2024-02-04
9,110,Aditya,aditya@email.com,ORD006,Received incorrect product,2024-02-05
10,111,Aditya,aditya@email.com,ORD006,Product delivered is different,2024-02-05
11,112,Neha,neha@email.com,ORD007,Refund not processed yet,2024-02-05
12,113,Neha,neha@email.com,ORD007,Still waiting for my refund,2024-02-06
13,114,Neha,neha@email.com,ORD007,My refund is not credited yet,2024-02-06
14,115,Ravi,ravi@email.com,ORD008,Received a damaged product,2024-02-06
15,116,Ravi,ravi@email.com,ORD008,The product I received is broken,2024-02-07
16,117,Ravi,ravi@email.com,ORD008,Item arrived with scratches,2024-02-07
17,118,Sonali,sonali@email.com,ORD009,How long does delivery take?,2024-02-07
18,119,Sonali,sonali@email.com,ORD009,When will my package arrive?,2024-02-08
19,120,Sonali,sonali@email.com,ORD009,Estimated delivery time?,2024-02-08

In [7]:
# df.duplicated()

In [9]:
df.duplicated(subset=['Customer_Name'], keep= 'last')
# Keep = False
# keep = 'first' , marks all duplicates True except the first occurence. 
# keep = 'last'  , marks all duplicates True except the last occurence.

0      True
1     False
2     False
3     False
4     False
5      True
6      True
7     False
8      True
9      True
10    False
11     True
12     True
13    False
14     True
15     True
16    False
17     True
18     True
19    False
dtype: bool

In [71]:
df.groupby('Customer_Name').size()
# df.groupby('Order_ID').size()

Customer_Name
Aditya    3
Aman      2
Neha      3
Priya     3
Ravi      3
Rohan     1
Rohit     1
Sneha     1
Sonali    3
dtype: int64

In [68]:
df.drop_duplicates()

,Ticket_ID,Customer_Name,Email,Order_ID,Issue_Description,Date
0,101,Aman,aman@email.com,ORD001,I can't log in to my account,2024-02-01
1,102,Rohit,rohit@email.com,ORD002,Login is not working for me,2024-02-02
2,103,Sneha,sneha@email.com,ORD003,Unable to log in to my account,2024-02-02
3,104,Rohan,rohan@email.com,ORD004,How to reset my password?,2024-02-03
4,105,Aman,aman@email.com,ORD001,I am unable to login to my account,2024-02-03
5,106,Priya,priya@email.com,ORD005,My order is delayed,2024-02-03
6,107,Priya,priya@email.com,ORD005,My order is late,2024-02-03
7,108,Priya,priya@email.com,ORD005,Order not received yet,2024-02-04
8,109,Aditya,aditya@email.com,ORD006,I got the wrong item,2024-02-04
9,110,Aditya,aditya@email.com,ORD006,Received incorrect product,2024-02-05
10,111,Aditya,aditya@email.com,ORD006,Product delivered is different,2024-02-05
11,112,Neha,neha@email.com,ORD007,Refund not processed yet,2024-02-05
12,113,Neha,neha@email.com,ORD007,Still waiting for my refund,2024-02-06
13,114,Neha,neha@email.com,ORD007,My refund is not credited yet,2024-02-06
14,115,Ravi,ravi@email.com,ORD008,Received a damaged product,2024-02-06
15,116,Ravi,ravi@email.com,ORD008,The product I received is broken,2024-02-07
16,117,Ravi,ravi@email.com,ORD008,Item arrived with scratches,2024-02-07
17,118,Sonali,sonali@email.com,ORD009,How long does delivery take?,2024-02-07
18,119,Sonali,sonali@email.com,ORD009,When will my package arrive?,2024-02-08
19,120,Sonali,sonali@email.com,ORD009,Estimated delivery time?,2024-02-08

In [69]:
df1 = df.drop_duplicates(subset =['Customer_Name'], keep = False)
df2 = df.drop_duplicates(subset =['Customer_Name'], keep = 'first')
df3 = df.drop_duplicates(subset =['Customer_Name'], keep = 'last')

In [70]:
df1

,Ticket_ID,Customer_Name,Email,Order_ID,Issue_Description,Date
1,102,Rohit,rohit@email.com,ORD002,Login is not working for me,2024-02-02
2,103,Sneha,sneha@email.com,ORD003,Unable to log in to my account,2024-02-02
3,104,Rohan,rohan@email.com,ORD004,How to reset my password?,2024-02-03

In [72]:
df2

,Ticket_ID,Customer_Name,Email,Order_ID,Issue_Description,Date
0,101,Aman,aman@email.com,ORD001,I can't log in to my account,2024-02-01
1,102,Rohit,rohit@email.com,ORD002,Login is not working for me,2024-02-02
2,103,Sneha,sneha@email.com,ORD003,Unable to log in to my account,2024-02-02
3,104,Rohan,rohan@email.com,ORD004,How to reset my password?,2024-02-03
5,106,Priya,priya@email.com,ORD005,My order is delayed,2024-02-03
8,109,Aditya,aditya@email.com,ORD006,I got the wrong item,2024-02-04
11,112,Neha,neha@email.com,ORD007,Refund not processed yet,2024-02-05
14,115,Ravi,ravi@email.com,ORD008,Received a damaged product,2024-02-06
17,118,Sonali,sonali@email.com,ORD009,How long does delivery take?,2024-02-07

In [73]:
df3

,Ticket_ID,Customer_Name,Email,Order_ID,Issue_Description,Date
1,102,Rohit,rohit@email.com,ORD002,Login is not working for me,2024-02-02
2,103,Sneha,sneha@email.com,ORD003,Unable to log in to my account,2024-02-02
3,104,Rohan,rohan@email.com,ORD004,How to reset my password?,2024-02-03
4,105,Aman,aman@email.com,ORD001,I am unable to login to my account,2024-02-03
7,108,Priya,priya@email.com,ORD005,Order not received yet,2024-02-04
10,111,Aditya,aditya@email.com,ORD006,Product delivered is different,2024-02-05
13,114,Neha,neha@email.com,ORD007,My refund is not credited yet,2024-02-06
16,117,Ravi,ravi@email.com,ORD008,Item arrived with scratches,2024-02-07
19,120,Sonali,sonali@email.com,ORD009,Estimated delivery time?,2024-02-08

In [12]:
df_ct = pd.read_excel(r'C:\Users\Arindham Krishna\Desktop\Data Engineer MIT\Data Sets\Customer Ticket\SFTicket.xlsx')

In [13]:
df_ct

,Date,Source,Region,CustomerID,Contact_Name,Contact,TicketID,Issue,Product,Description
0,2025-02-01,Phone,AMER,HO045,Jonathan H,jonathan@gmail.com,250201,Not reporting,Panel,"My panel is not showing any information, I am ..."
1,2025-02-02,Chat,EMEA,HO197,Mike Wayne,mike22@gmail.com,250202,Wifi Issue,Channel,Unable to connect my channel to my new wifi
2,2025-02-03,Email,EMEA,HO197,Mike Kelly,mikekelly.97@gmail.com,250203,Comms loss,Channel,Channel keeps getting disconnected
3,2025-02-03,Web,AUSNZ,IN387,Venessa,venessa@yahoo.com,250204,Power Loss,Channel,Can you please send someone as I do not see an...
4,2025-02-05,Phone,AMER,HO045,Jonathan Han,jonathan@yahoo.com,250205,Short Circuit,Panel,Looks like there is no power in panels
5,2025-02-06,Chat,APAC,IN254,Ray Solar,raysolar@yahoo.com,250206,Heating issue,Bat,"Customers says that bat is heating up a lot, d..."
6,2025-02-08,Chat,EMEA,IN155,Richard Dutch Sun,richard@dutchsun.com,250207,Production issue,Panel,"No information displayed for panel, looks like..."
7,2025-02-08,Email,AUSNZ,HO390,Mike Chew,mike@yahoo.com,250208,Connectivity issue,Channel,We had wifi down yesterday in queensland austr...
8,2025-02-10,Web,APAC,IN254,Dheeraj Ray Solar,dheeraj@yahoo.com,250209,Heatup Wire Damage,Bat,We require new wires to be sent as replacement...
9,2025-02-11,Phone,AMER,HO101,Ricky,ricky@gmail.com,250210,Login Issue,App,I am unable to login into my application and m...
10,2025-02-12,Email,EMEA,IN155,Dutch Sun,official@dutchsun.com,250211,Power failure,Channel,"No response on our issue, can you please confi..."
11,2025-02-12,Web,AUSNZ,HO324,Kevin,kevin@yahoo.com,250212,ProductionLoss,Panel,My system no power since many days
12,2025-02-14,Phone,AMER,HO011,Kevin Marshal,kevinmarshal@gmail.com,250213,Backup fail,Bat,Bat failed to backup when outage. Need compens...
13,2025-02-15,Chat,APAC,IN203,Grand Power,grandpower@gmail.com,250214,Replacement,Panel,Replace my panels or take it away!
14,2025-02-16,Email,EMEA,IN107,Netherland Power,netherlandpower@yahoo.com,250215,Communication Loss,Channel,Channel keeps getting disconnected though on 2...

In [33]:
df_ct.columns

Index(['Date', 'Source', 'Region', 'CustomerID', 'Contact_Name', 'Contact ',
       'TicketID', 'Issue', 'Product', 'Description'],
      dtype='object')

In [21]:
# !pip install fuzzywuzzy
# from fuzzywuzzy import fuzz
# fuzz.ratio

In [22]:
# print(fuzz.ratio("Arindham Krish", "Arindham Krishna"))

In [25]:
# !pip install rapidfuzz
from rapidfuzz import fuzz

In [41]:
def find_near_duplicates(df_ct, column, threshold = 70):
    duplicates =[]
    for i in range (len(df_ct)):
        for j in range(i+1, len(df_ct)): 
            similarity = fuzz.ratio(df_ct[column][i],df_ct[column][j])
            if similarity >= threshold:
                duplicates.append((df_ct['TicketID'][i],df_ct['TicketID'][j], similarity))
    
    return duplicates

In [52]:
near_duplicates = find_near_duplicates(df_ct,'CustomerID',threshold = 80)
print("Near duplicates from data set:")
for dup in near_duplicates: 
    print(f'Ticket {dup[0]} and Ticket {dup[1]} are {round(dup[2],2)}% similar.')

Near duplicates from data set:
Ticket 250201 and Ticket 250205 are 100.0% similar.
Ticket 250202 and Ticket 250203 are 100.0% similar.
Ticket 250206 and Ticket 250209 are 100.0% similar.
Ticket 250207 and Ticket 250211 are 100.0% similar.
Ticket 250210 and Ticket 250213 are 80.0% similar.

In [55]:
# !pip install recordlinkage
import recordlinkage

In [58]:
# step 1: set up an indexer 
indexer = recordlinkage.Index()
indexer.full() 
links = indexer.index(df_ct)

WARNING:recordlinkage:indexing - performance warning - A full index can result in large number of record pairs.

In [66]:
# compare records based on similarity 
compare = recordlinkage.Compare()

# compare using string similarity
compare.string('Contact_Name','Contact_Name',method ='jarowinkler', threshold = 0.7, label = 'name_similarity_JW')

compare.string('Contact ','Contact ',method ='levenshtein', threshold = 0.7, label = 'email_similarity_LS')

compare.exact('Contact ','Contact ',label = 'contact_similarity')

features = compare.compute(links,df_ct)

potential_duplicates = features[(features.sum(axis=1)>=2)]
print(potential_duplicates)

     name_similarity_JW  email_similarity_LS  contact_similarity
4 0                 1.0                  1.0                   0